# Generated by Django 4.0.3 on 2022-12-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvo',
            name='import_href',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
